---

- name: Create a directory if it does not exist
  file:
    path: /usr/local/harbor
    state: directory
    mode: '0755'

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: https://github.com/goharbor/harbor/releases/download/v1.10.1/harbor-offline-installer-v1.10.1.tgz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/harbor/harbor.yml
    #register: downloaded

- name: check if file exists
  stat: 
    path: /usr/local/harbor/docker-compose.yml
  register: docker_compose_file_exists



